services:
    david63.copynewtopic.listener:
        class: david63\copynewtopic\event\listener
        arguments:
            - '%core.table_prefix%'
            - '@config'
            - '@user'			
            - '@log'
        tags:
            - { name: event.listener }

    david63.copynewtopic.admin.controller:
        class: david63\copynewtopic\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@service_container'
